// Mock data for artists
export const artistsData = [
  {
    id: "1",
    name: "Sarah Johnson",
    category: "Singer",
    bio: "Professional vocalist with 10+ years of experience in jazz, pop, and classical music. Perfect for weddings, corporate events, and intimate gatherings.",
    location: "New York, NY",
    priceRange: "$1000-2500",
    rating: 4.9,
    reviews: 127,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    category: "DJ",
    bio: "High-energy DJ specializing in electronic, hip-hop, and Latin music. Bringing the party to life with state-of-the-art equipment and crowd-reading skills.",
    location: "Los Angeles, CA",
    priceRange: "$500-1000",
    rating: 4.8,
    reviews: 89,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "3",
    name: "Elena Petrov",
    category: "Dancer",
    bio: "Contemporary and ballet dancer with international performance experience. Choreographer for special events and artistic performances.",
    location: "Chicago, IL",
    priceRange: "$1000-2500",
    rating: 4.9,
    reviews: 156,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    category: "Speaker",
    bio: "Motivational speaker and business consultant with expertise in leadership, innovation, and team building. Engaging presentations for corporate events.",
    location: "Austin, TX",
    priceRange: "$2500-5000",
    rating: 4.7,
    reviews: 73,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "5",
    name: "Aria Chen",
    category: "Singer",
    bio: "Versatile vocalist fluent in multiple languages, specializing in world music, opera, and contemporary styles. Perfect for multicultural events.",
    location: "San Francisco, CA",
    priceRange: "$1000-2500",
    rating: 4.8,
    reviews: 94,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "6",
    name: "Tony Martinez",
    category: "Dancer",
    bio: "Latin dance specialist with expertise in salsa, bachata, and tango. Professional instructor and performer for events and celebrations.",
    location: "Miami, FL",
    priceRange: "$500-1000",
    rating: 4.9,
    reviews: 112,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "7",
    name: "DJ Luna",
    category: "DJ",
    bio: "Electronic music producer and DJ with a unique style blending house, techno, and ambient sounds. Perfect for upscale events and festivals.",
    location: "Seattle, WA",
    priceRange: "$1000-2500",
    rating: 4.6,
    reviews: 67,
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "8",
    name: "Rebecca Thompson",
    category: "Speaker",
    bio: "Tech industry expert and keynote speaker focusing on digital transformation, AI, and future of work. Inspiring presentations for conferences.",
    location: "Boston, MA",
    priceRange: "$2500-5000",
    rating: 4.8,
    reviews: 45,
    image: "/placeholder.svg?height=300&width=300",
  },
]

// Mock data for managed artists (dashboard)
export const managedArtists = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    category: "Singer",
    location: "New York, NY",
    priceRange: "$1000-2500",
    rating: 4.9,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    email: "marcus.rodriguez@email.com",
    category: "DJ",
    location: "Los Angeles, CA",
    priceRange: "$500-1000",
    rating: 4.8,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "3",
    name: "Elena Petrov",
    email: "elena.petrov@email.com",
    category: "Dancer",
    location: "Chicago, IL",
    priceRange: "$1000-2500",
    rating: 4.9,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    email: "james.wilson@email.com",
    category: "Speaker",
    location: "Austin, TX",
    priceRange: "$2500-5000",
    rating: 4.7,
    image: "/placeholder.svg?height=100&width=100",
  },
]

// Mock data for booking requests
export const bookingRequests = [
  {
    id: "1",
    eventName: "Corporate Annual Gala",
    clientName: "TechCorp Inc.",
    artistName: "Sarah Johnson",
    eventDate: "2024-07-15",
    budget: "$2,000",
    status: "pending" as const,
  },
  {
    id: "2",
    eventName: "Wedding Reception",
    clientName: "John & Mary Smith",
    artistName: "Marcus Rodriguez",
    eventDate: "2024-07-22",
    budget: "$800",
    status: "confirmed" as const,
  },
  {
    id: "3",
    eventName: "Art Gallery Opening",
    clientName: "Modern Art Gallery",
    artistName: "Elena Petrov",
    eventDate: "2024-08-05",
    budget: "$1,500",
    status: "confirmed" as const,
  },
  {
    id: "4",
    eventName: "Business Conference",
    clientName: "Innovation Summit",
    artistName: "Dr. James Wilson",
    eventDate: "2024-08-12",
    budget: "$3,500",
    status: "pending" as const,
  },
  {
    id: "5",
    eventName: "Birthday Party",
    clientName: "Lisa Anderson",
    artistName: "Marcus Rodriguez",
    eventDate: "2024-07-30",
    budget: "$600",
    status: "rejected" as const,
  },
]
